"""empty message

Revision ID: 33458e785b53
Revises: 
Create Date: 2018-09-27 15:31:21.846475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33458e785b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Task_timestamp'), 'Task', ['timestamp'], unique=False)
    op.create_table('subTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subTask')
    op.drop_index(op.f('ix_Task_timestamp'), table_name='Task')
    op.drop_table('Task')
    # ### end Alembic commands ###
