"""Added subtasks, images, finishdate

Revision ID: ee0acee5e55f
Revises: 33458e785b53
Create Date: 2018-09-27 18:40:40.647848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0acee5e55f'
down_revision = '33458e785b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('finishdate', sa.DateTime(), nullable=True))
    op.add_column('Task', sa.Column('image', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_Task_finishdate'), 'Task', ['finishdate'], unique=False)
    op.add_column('subTask', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subTask', 'Task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subTask', type_='foreignkey')
    op.drop_column('subTask', 'task_id')
    op.drop_index(op.f('ix_Task_finishdate'), table_name='Task')
    op.drop_column('Task', 'image')
    op.drop_column('Task', 'finishdate')
    # ### end Alembic commands ###
