"""empty message

Revision ID: f8a4401177eb
Revises: 
Create Date: 2018-10-08 18:20:58.736117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a4401177eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('finishdate', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Task_finishdate'), 'Task', ['finishdate'], unique=False)
    op.create_index(op.f('ix_Task_timestamp'), 'Task', ['timestamp'], unique=False)
    op.create_table('subTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['Task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subTask')
    op.drop_index(op.f('ix_Task_timestamp'), table_name='Task')
    op.drop_index(op.f('ix_Task_finishdate'), table_name='Task')
    op.drop_table('Task')
    # ### end Alembic commands ###
